const express= require('express')
const router=express.Router()
const userController=require('../controller/userController')
const turfController=require('../controller/turfController')
const bookingController=require('../controller/bookingController')
const reviewController=require('../controller/reviewController')
const clubController=require('../controller/clubController')
const chatController=require('../controller/chatController')
const tournamentController=require('../controller/tournamentController')
const auth=require("../middleware/auth")
const multer=require("../config/multer")
const upload=multer.createMulter()

router.post('/signUp',userController.signUp)
router.post('/verify',userController.verifyMail)
router.post('/login',userController.login)
router.post('/forgotPassword',userController.forgotPassword)
router.post('/resetPassword',userController.resetPassword)
router.post('/googlelogin',userController.googlelogin)
router.get('/getTurfs',turfController.getTurfs)
router.get('/profile',auth.verifyToken,userController.userProfile)
router.get('/getUserDetail',auth.verifyToken,userController.getUserDetail)
router.post('/userEdit',auth.verifyToken,userController.editProfile)
router.get('/getTurfDetail',auth.verifyToken,turfController.getTurfDetail)
router.post('/otpLogin',userController.otpLogin)
router.post('/bookingSuccess',auth.verifyToken,bookingController.paymentSuccess)
router.get('/bookingHistory',auth.verifyToken,bookingController.bookingHistory)
router.post('/create-checkout-session',auth.verifyToken,bookingController.createCheckOut)
router.post('/addReview',auth.verifyToken,reviewController.addReview)
router.get('/reviews',auth.verifyToken,reviewController.getReview)
router.post('/createClub',auth.verifyToken,clubController.createClub)
router.get('/getClubs',auth.verifyToken,clubController.getClubs)
router.post('/joinClub',auth.verifyToken,clubController.joinClub)
router.post('/acceptMember',auth.verifyToken,clubController.acceptMember)
router.get('/yourClubs',auth.verifyToken,clubController.yourClubs)
router.get('/createdClubs',auth.verifyToken,clubController.createdClubs)
router.get('/getMembers',auth.verifyToken,clubController.getMembers)
router.get('/clubMembers',auth.verifyToken,clubController.clubMembers)
router.post('/removeMember',auth.verifyToken,clubController.removeMember)
router.post('/clubDetails',auth.verifyToken,clubController.clubDetails)
router.post('/clubGalleryAdd',upload.single('file'),auth.verifyToken,clubController.clubGalleryAdd)
router.post('/getGallery',auth.verifyToken,clubController.getGallery)
router.post('/removeGallery',auth.verifyToken,clubController.removeGallery)
router.post('/clubUserDetails',auth.verifyToken,clubController.userClubDetails)
router.post('/addMessage',auth.verifyToken,chatController.addMessage)
router.post('/getMessage',auth.verifyToken,chatController.getMessage)
router.get('/getTournaments',auth.verifyToken,tournamentController.getTournaments)
router.get('/leaveTournament',auth.verifyToken,tournamentController.leaveTournament)
router.get('/cancelTournament',auth.verifyToken,tournamentController.cancelTournament)
router.get('/getTournamentDetails',auth.verifyToken,tournamentController.getTournamentDetails)
router.get('/getYourTournaments',auth.verifyToken,tournamentController.getYourTournaments)
router.get('/getJoinedTournaments',auth.verifyToken,tournamentController.getJoinedTournaments)
router.post('/joinTournament',auth.verifyToken,tournamentController.joinTournament)
router.post('/createTournament',upload.single('detailedDocument'),auth.verifyToken,tournamentController.createTournament)
router.post('/editTournament',upload.single('detailedDocument'),auth.verifyToken,tournamentController.editTournament)
router.post('/addGame',auth.verifyToken,tournamentController.addGame)
router.get('/findMatches',auth.verifyToken,tournamentController.findMatches)
router.post('/deleteGame',auth.verifyToken,tournamentController.deleteGame)
router.post('/editGame',auth.verifyToken,tournamentController.editGame)
router.post('/addWinners',auth.verifyToken,tournamentController.addWinners)






module.exports=router
